### ISSUE TITLE
Errors running bash a11ytester.sh https://benefits.gov

### ISSUE THREAD

**Issue by kamal2222ahmed** [mikaelvesavuori/a11ytester-action#1]
bash a11ytester.sh https://benefits.gov
Running Webhint test...
a11ytester.sh: line 28: hint: command not found
mv: rename hint-report to webhint: No such file or directory
mv: rename webhint to results/benefitsgov/webhint: No such file or directory
Running axe test...
a11ytester.sh: line 33: axe: command not found
Running pa11y test...
a11ytester.sh: line 39: pa11y: command not found
Running Lighthouse test...
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +507ms
  LH:ChromeLauncher Waiting for browser....... +504ms
  LH:ChromeLauncher Waiting for browser......... +503ms
  LH:ChromeLauncher Waiting for browser........... +503ms
  LH:ChromeLauncher Waiting for browser............. +505ms
  LH:ChromeLauncher Waiting for browser............... +506ms
  LH:ChromeLauncher Waiting for browser................. +504ms
  LH:ChromeLauncher Waiting for browser................... +502ms
  LH:ChromeLauncher Waiting for browser...................✓ +10ms
  LH:status Connecting to browser +698ms
  LH:status Navigating to about:blank +7ms
  LH:status Benchmarking machine +8ms

**Comment by mikaelvesavuori** [comment]
Hi @kamal2222ahmed!

Based on the filename `a11ytester.sh` I assume you refer to [a11ytester](https://github.com/mikaelvesavuori/a11ytester), not to this action utilizing it. While `a11ytester` is a set of scripts you can run on your computer, this repo represents a (flaky) GitHub Actions subset of those scripts.

Given that I am the author of both projects, though, it does seem as your issue is of a missing or incomplete installation. Please refer to the docs to understand how to install the packages (axe, Webhint, etc.).

I've also added a clarification that the project assumes Linux or Mac. If you are on Windows you'll have to "translate" the script steps into something that works there.

**Comment by mikaelvesavuori** [comment]
I will close this as it is installation-related and part of another project.
